// Copyright 2023 The Blocky Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: blocky/authz/admin/v1alpha/instance_admin.proto

package authzadminv1alphaconnect

import (
	context "context"
	errors "errors"
	v1alpha "github.com/blockysource/go-genproto/blocky/authz/admin/v1alpha"
	connect_go "github.com/bufbuild/connect-go"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// InstanceAdminServiceName is the fully-qualified name of the InstanceAdminService service.
	InstanceAdminServiceName = "blocky.authz.admin.v1alpha.InstanceAdminService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// InstanceAdminServiceUpdateInstanceProcedure is the fully-qualified name of the
	// InstanceAdminService's UpdateInstance RPC.
	InstanceAdminServiceUpdateInstanceProcedure = "/blocky.authz.admin.v1alpha.InstanceAdminService/UpdateInstance"
	// InstanceAdminServiceGetInstanceProcedure is the fully-qualified name of the
	// InstanceAdminService's GetInstance RPC.
	InstanceAdminServiceGetInstanceProcedure = "/blocky.authz.admin.v1alpha.InstanceAdminService/GetInstance"
)

// InstanceAdminServiceClient is a client for the blocky.authz.admin.v1alpha.InstanceAdminService
// service.
type InstanceAdminServiceClient interface {
	// Patch an existing instance of an Authorization service.
	UpdateInstance(context.Context, *connect_go.Request[v1alpha.UpdateInstanceRequest]) (*connect_go.Response[v1alpha.Instance], error)
	// Gets the details of an instance of an Authorization service.
	GetInstance(context.Context, *connect_go.Request[v1alpha.GetInstanceRequest]) (*connect_go.Response[v1alpha.Instance], error)
}

// NewInstanceAdminServiceClient constructs a client for the
// blocky.authz.admin.v1alpha.InstanceAdminService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewInstanceAdminServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) InstanceAdminServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &instanceAdminServiceClient{
		updateInstance: connect_go.NewClient[v1alpha.UpdateInstanceRequest, v1alpha.Instance](
			httpClient,
			baseURL+InstanceAdminServiceUpdateInstanceProcedure,
			opts...,
		),
		getInstance: connect_go.NewClient[v1alpha.GetInstanceRequest, v1alpha.Instance](
			httpClient,
			baseURL+InstanceAdminServiceGetInstanceProcedure,
			opts...,
		),
	}
}

// instanceAdminServiceClient implements InstanceAdminServiceClient.
type instanceAdminServiceClient struct {
	updateInstance *connect_go.Client[v1alpha.UpdateInstanceRequest, v1alpha.Instance]
	getInstance    *connect_go.Client[v1alpha.GetInstanceRequest, v1alpha.Instance]
}

// UpdateInstance calls blocky.authz.admin.v1alpha.InstanceAdminService.UpdateInstance.
func (c *instanceAdminServiceClient) UpdateInstance(ctx context.Context, req *connect_go.Request[v1alpha.UpdateInstanceRequest]) (*connect_go.Response[v1alpha.Instance], error) {
	return c.updateInstance.CallUnary(ctx, req)
}

// GetInstance calls blocky.authz.admin.v1alpha.InstanceAdminService.GetInstance.
func (c *instanceAdminServiceClient) GetInstance(ctx context.Context, req *connect_go.Request[v1alpha.GetInstanceRequest]) (*connect_go.Response[v1alpha.Instance], error) {
	return c.getInstance.CallUnary(ctx, req)
}

// InstanceAdminServiceHandler is an implementation of the
// blocky.authz.admin.v1alpha.InstanceAdminService service.
type InstanceAdminServiceHandler interface {
	// Patch an existing instance of an Authorization service.
	UpdateInstance(context.Context, *connect_go.Request[v1alpha.UpdateInstanceRequest]) (*connect_go.Response[v1alpha.Instance], error)
	// Gets the details of an instance of an Authorization service.
	GetInstance(context.Context, *connect_go.Request[v1alpha.GetInstanceRequest]) (*connect_go.Response[v1alpha.Instance], error)
}

// NewInstanceAdminServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewInstanceAdminServiceHandler(svc InstanceAdminServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	instanceAdminServiceUpdateInstanceHandler := connect_go.NewUnaryHandler(
		InstanceAdminServiceUpdateInstanceProcedure,
		svc.UpdateInstance,
		opts...,
	)
	instanceAdminServiceGetInstanceHandler := connect_go.NewUnaryHandler(
		InstanceAdminServiceGetInstanceProcedure,
		svc.GetInstance,
		opts...,
	)
	return "/blocky.authz.admin.v1alpha.InstanceAdminService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case InstanceAdminServiceUpdateInstanceProcedure:
			instanceAdminServiceUpdateInstanceHandler.ServeHTTP(w, r)
		case InstanceAdminServiceGetInstanceProcedure:
			instanceAdminServiceGetInstanceHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedInstanceAdminServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedInstanceAdminServiceHandler struct{}

func (UnimplementedInstanceAdminServiceHandler) UpdateInstance(context.Context, *connect_go.Request[v1alpha.UpdateInstanceRequest]) (*connect_go.Response[v1alpha.Instance], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("blocky.authz.admin.v1alpha.InstanceAdminService.UpdateInstance is not implemented"))
}

func (UnimplementedInstanceAdminServiceHandler) GetInstance(context.Context, *connect_go.Request[v1alpha.GetInstanceRequest]) (*connect_go.Response[v1alpha.Instance], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("blocky.authz.admin.v1alpha.InstanceAdminService.GetInstance is not implemented"))
}
