// Copyright 2023 The Blocky Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: blocky/mailing/admin/v1alpha/admin_attachments.proto

package mailingv1alpha

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const ()

// AttachmentsAdminServiceClient is the client API for AttachmentsAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AttachmentsAdminServiceClient interface {
}

type attachmentsAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAttachmentsAdminServiceClient(cc grpc.ClientConnInterface) AttachmentsAdminServiceClient {
	return &attachmentsAdminServiceClient{cc}
}

// AttachmentsAdminServiceServer is the server API for AttachmentsAdminService service.
// All implementations must embed UnimplementedAttachmentsAdminServiceServer
// for forward compatibility
type AttachmentsAdminServiceServer interface {
	mustEmbedUnimplementedAttachmentsAdminServiceServer()
}

// UnimplementedAttachmentsAdminServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAttachmentsAdminServiceServer struct {
}

func (UnimplementedAttachmentsAdminServiceServer) mustEmbedUnimplementedAttachmentsAdminServiceServer() {
}

// UnsafeAttachmentsAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AttachmentsAdminServiceServer will
// result in compilation errors.
type UnsafeAttachmentsAdminServiceServer interface {
	mustEmbedUnimplementedAttachmentsAdminServiceServer()
}

func RegisterAttachmentsAdminServiceServer(s grpc.ServiceRegistrar, srv AttachmentsAdminServiceServer) {
	s.RegisterService(&AttachmentsAdminService_ServiceDesc, srv)
}

// AttachmentsAdminService_ServiceDesc is the grpc.ServiceDesc for AttachmentsAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AttachmentsAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blocky.mailing.v1alpha.AttachmentsAdminService",
	HandlerType: (*AttachmentsAdminServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "blocky/mailing/admin/v1alpha/admin_attachments.proto",
}
