// Copyright 2023 The Blocky Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: blocky/kms/cloud/v1alpha/cloud_kms_service.proto

package kmscloudpb

import (
	context "context"
	crypto "github.com/blockysource/go-genproto/blocky/type/crypto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CloudKeyManagementService_CreateKey_FullMethodName               = "/blocky.kms.cloud.v1alpha.CloudKeyManagementService/CreateKey"
	CloudKeyManagementService_ListKeys_FullMethodName                = "/blocky.kms.cloud.v1alpha.CloudKeyManagementService/ListKeys"
	CloudKeyManagementService_GetKey_FullMethodName                  = "/blocky.kms.cloud.v1alpha.CloudKeyManagementService/GetKey"
	CloudKeyManagementService_UpdateKey_FullMethodName               = "/blocky.kms.cloud.v1alpha.CloudKeyManagementService/UpdateKey"
	CloudKeyManagementService_DeleteKey_FullMethodName               = "/blocky.kms.cloud.v1alpha.CloudKeyManagementService/DeleteKey"
	CloudKeyManagementService_RotateKey_FullMethodName               = "/blocky.kms.cloud.v1alpha.CloudKeyManagementService/RotateKey"
	CloudKeyManagementService_GetKeyMaterial_FullMethodName          = "/blocky.kms.cloud.v1alpha.CloudKeyManagementService/GetKeyMaterial"
	CloudKeyManagementService_ListKeyMaterials_FullMethodName        = "/blocky.kms.cloud.v1alpha.CloudKeyManagementService/ListKeyMaterials"
	CloudKeyManagementService_GetKeyMaterialCryptoKey_FullMethodName = "/blocky.kms.cloud.v1alpha.CloudKeyManagementService/GetKeyMaterialCryptoKey"
	CloudKeyManagementService_CreateKeyRing_FullMethodName           = "/blocky.kms.cloud.v1alpha.CloudKeyManagementService/CreateKeyRing"
	CloudKeyManagementService_ListKeyRings_FullMethodName            = "/blocky.kms.cloud.v1alpha.CloudKeyManagementService/ListKeyRings"
	CloudKeyManagementService_GetKeyRing_FullMethodName              = "/blocky.kms.cloud.v1alpha.CloudKeyManagementService/GetKeyRing"
	CloudKeyManagementService_ListKeyRingPublicKeys_FullMethodName   = "/blocky.kms.cloud.v1alpha.CloudKeyManagementService/ListKeyRingPublicKeys"
	CloudKeyManagementService_UpdateKeyRing_FullMethodName           = "/blocky.kms.cloud.v1alpha.CloudKeyManagementService/UpdateKeyRing"
	CloudKeyManagementService_DeleteKeyRing_FullMethodName           = "/blocky.kms.cloud.v1alpha.CloudKeyManagementService/DeleteKeyRing"
	CloudKeyManagementService_SignBlob_FullMethodName                = "/blocky.kms.cloud.v1alpha.CloudKeyManagementService/SignBlob"
	CloudKeyManagementService_VerifyBlob_FullMethodName              = "/blocky.kms.cloud.v1alpha.CloudKeyManagementService/VerifyBlob"
	CloudKeyManagementService_SignContent_FullMethodName             = "/blocky.kms.cloud.v1alpha.CloudKeyManagementService/SignContent"
	CloudKeyManagementService_VerifySignedContent_FullMethodName     = "/blocky.kms.cloud.v1alpha.CloudKeyManagementService/VerifySignedContent"
	CloudKeyManagementService_EncryptContent_FullMethodName          = "/blocky.kms.cloud.v1alpha.CloudKeyManagementService/EncryptContent"
	CloudKeyManagementService_DecryptContent_FullMethodName          = "/blocky.kms.cloud.v1alpha.CloudKeyManagementService/DecryptContent"
	CloudKeyManagementService_EncryptBlob_FullMethodName             = "/blocky.kms.cloud.v1alpha.CloudKeyManagementService/EncryptBlob"
	CloudKeyManagementService_DecryptBlob_FullMethodName             = "/blocky.kms.cloud.v1alpha.CloudKeyManagementService/DecryptBlob"
)

// CloudKeyManagementServiceClient is the client API for CloudKeyManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CloudKeyManagementServiceClient interface {
	// CreateKey creates a new cryptographic key.
	// New key is neither active nor used in a set.
	CreateKey(ctx context.Context, in *CreateKeyRequest, opts ...grpc.CallOption) (*Key, error)
	// Lists the keys for a given project.
	ListKeys(ctx context.Context, in *ListKeysRequest, opts ...grpc.CallOption) (*ListKeysResponse, error)
	// Get a key by its resource name.
	GetKey(ctx context.Context, in *GetKeyRequest, opts ...grpc.CallOption) (*Key, error)
	// UpdateKey updates the specified cryptographic key.
	UpdateKey(ctx context.Context, in *UpdateKeyRequest, opts ...grpc.CallOption) (*Key, error)
	// DeleteKey deletes the specified cryptographic key.
	// If the key is protected it will result in an error of type PERMISSION_DENIED.
	DeleteKey(ctx context.Context, in *DeleteKeyRequest, opts ...grpc.CallOption) (*Key, error)
	// Creates a new key material and rotates the key.
	RotateKey(ctx context.Context, in *RotateKeyRequest, opts ...grpc.CallOption) (*Key, error)
	// GetKeyMaterial returns the specified key material.
	GetKeyMaterial(ctx context.Context, in *GetKeyMaterialRequest, opts ...grpc.CallOption) (*KeyMaterial, error)
	// ListKeyMaterials lists cryptographic keys that matches given request.
	ListKeyMaterials(ctx context.Context, in *ListKeyMaterialsRequest, opts ...grpc.CallOption) (*ListKeyMaterialsResponse, error)
	// GetKeyMaterialCryptoKey returns the specified key material.
	GetKeyMaterialCryptoKey(ctx context.Context, in *GetKeyMaterialRequest, opts ...grpc.CallOption) (*KeyMaterialContent, error)
	// Create a new key ring.
	CreateKeyRing(ctx context.Context, in *CreateKeyRingRequest, opts ...grpc.CallOption) (*KeyRing, error)
	// List key rings.
	ListKeyRings(ctx context.Context, in *ListKeyRingsRequest, opts ...grpc.CallOption) (*ListKeyRingsResponse, error)
	// Get key ring.
	GetKeyRing(ctx context.Context, in *GetKeyRingRequest, opts ...grpc.CallOption) (*KeyRing, error)
	// ListKeyRingPublicKeys lists the asymmetric public keys for a given key rings key materials.
	ListKeyRingPublicKeys(ctx context.Context, in *ListKeyRingPublicKeysRequest, opts ...grpc.CallOption) (*ListKeyRingPublicKeysResponse, error)
	// Update key ring.
	UpdateKeyRing(ctx context.Context, in *UpdateKeyRingRequest, opts ...grpc.CallOption) (*KeyRing, error)
	// Delete key ring.
	DeleteKeyRing(ctx context.Context, in *DeleteKeyRingRequest, opts ...grpc.CallOption) (*KeyRing, error)
	// SignBlob signs the given data with the given key.
	SignBlob(ctx context.Context, in *SignBlobRequest, opts ...grpc.CallOption) (*SignBlobResponse, error)
	// VerifyBlob verifies the given signature with the given key.
	VerifyBlob(ctx context.Context, in *VerifyBlobRequest, opts ...grpc.CallOption) (*VerifyBlobResponse, error)
	// SignContent signs the given data with the given key.
	SignContent(ctx context.Context, in *SignContentRequest, opts ...grpc.CallOption) (*crypto.SignedContent, error)
	// Verify signed content verifies the given signature with the given key.
	VerifySignedContent(ctx context.Context, in *VerifySignedContentRequest, opts ...grpc.CallOption) (*VerifySignedContentResponse, error)
	// Encrypts the input content with the given key.
	EncryptContent(ctx context.Context, in *EncryptContentRequest, opts ...grpc.CallOption) (*EncryptContentResponse, error)
	// Decrypts the input content with the given key.
	DecryptContent(ctx context.Context, in *DecryptContentRequest, opts ...grpc.CallOption) (*DecryptContentResponse, error)
	// EncryptBlob encrypts the input blob with the given key.
	EncryptBlob(ctx context.Context, in *EncryptBlobRequest, opts ...grpc.CallOption) (*EncryptBlobResponse, error)
	// DecryptBlob decrypts the input blob with the given key.
	DecryptBlob(ctx context.Context, in *DecryptBlobRequest, opts ...grpc.CallOption) (*DecryptBlobResponse, error)
}

type cloudKeyManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCloudKeyManagementServiceClient(cc grpc.ClientConnInterface) CloudKeyManagementServiceClient {
	return &cloudKeyManagementServiceClient{cc}
}

func (c *cloudKeyManagementServiceClient) CreateKey(ctx context.Context, in *CreateKeyRequest, opts ...grpc.CallOption) (*Key, error) {
	out := new(Key)
	err := c.cc.Invoke(ctx, CloudKeyManagementService_CreateKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudKeyManagementServiceClient) ListKeys(ctx context.Context, in *ListKeysRequest, opts ...grpc.CallOption) (*ListKeysResponse, error) {
	out := new(ListKeysResponse)
	err := c.cc.Invoke(ctx, CloudKeyManagementService_ListKeys_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudKeyManagementServiceClient) GetKey(ctx context.Context, in *GetKeyRequest, opts ...grpc.CallOption) (*Key, error) {
	out := new(Key)
	err := c.cc.Invoke(ctx, CloudKeyManagementService_GetKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudKeyManagementServiceClient) UpdateKey(ctx context.Context, in *UpdateKeyRequest, opts ...grpc.CallOption) (*Key, error) {
	out := new(Key)
	err := c.cc.Invoke(ctx, CloudKeyManagementService_UpdateKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudKeyManagementServiceClient) DeleteKey(ctx context.Context, in *DeleteKeyRequest, opts ...grpc.CallOption) (*Key, error) {
	out := new(Key)
	err := c.cc.Invoke(ctx, CloudKeyManagementService_DeleteKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudKeyManagementServiceClient) RotateKey(ctx context.Context, in *RotateKeyRequest, opts ...grpc.CallOption) (*Key, error) {
	out := new(Key)
	err := c.cc.Invoke(ctx, CloudKeyManagementService_RotateKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudKeyManagementServiceClient) GetKeyMaterial(ctx context.Context, in *GetKeyMaterialRequest, opts ...grpc.CallOption) (*KeyMaterial, error) {
	out := new(KeyMaterial)
	err := c.cc.Invoke(ctx, CloudKeyManagementService_GetKeyMaterial_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudKeyManagementServiceClient) ListKeyMaterials(ctx context.Context, in *ListKeyMaterialsRequest, opts ...grpc.CallOption) (*ListKeyMaterialsResponse, error) {
	out := new(ListKeyMaterialsResponse)
	err := c.cc.Invoke(ctx, CloudKeyManagementService_ListKeyMaterials_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudKeyManagementServiceClient) GetKeyMaterialCryptoKey(ctx context.Context, in *GetKeyMaterialRequest, opts ...grpc.CallOption) (*KeyMaterialContent, error) {
	out := new(KeyMaterialContent)
	err := c.cc.Invoke(ctx, CloudKeyManagementService_GetKeyMaterialCryptoKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudKeyManagementServiceClient) CreateKeyRing(ctx context.Context, in *CreateKeyRingRequest, opts ...grpc.CallOption) (*KeyRing, error) {
	out := new(KeyRing)
	err := c.cc.Invoke(ctx, CloudKeyManagementService_CreateKeyRing_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudKeyManagementServiceClient) ListKeyRings(ctx context.Context, in *ListKeyRingsRequest, opts ...grpc.CallOption) (*ListKeyRingsResponse, error) {
	out := new(ListKeyRingsResponse)
	err := c.cc.Invoke(ctx, CloudKeyManagementService_ListKeyRings_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudKeyManagementServiceClient) GetKeyRing(ctx context.Context, in *GetKeyRingRequest, opts ...grpc.CallOption) (*KeyRing, error) {
	out := new(KeyRing)
	err := c.cc.Invoke(ctx, CloudKeyManagementService_GetKeyRing_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudKeyManagementServiceClient) ListKeyRingPublicKeys(ctx context.Context, in *ListKeyRingPublicKeysRequest, opts ...grpc.CallOption) (*ListKeyRingPublicKeysResponse, error) {
	out := new(ListKeyRingPublicKeysResponse)
	err := c.cc.Invoke(ctx, CloudKeyManagementService_ListKeyRingPublicKeys_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudKeyManagementServiceClient) UpdateKeyRing(ctx context.Context, in *UpdateKeyRingRequest, opts ...grpc.CallOption) (*KeyRing, error) {
	out := new(KeyRing)
	err := c.cc.Invoke(ctx, CloudKeyManagementService_UpdateKeyRing_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudKeyManagementServiceClient) DeleteKeyRing(ctx context.Context, in *DeleteKeyRingRequest, opts ...grpc.CallOption) (*KeyRing, error) {
	out := new(KeyRing)
	err := c.cc.Invoke(ctx, CloudKeyManagementService_DeleteKeyRing_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudKeyManagementServiceClient) SignBlob(ctx context.Context, in *SignBlobRequest, opts ...grpc.CallOption) (*SignBlobResponse, error) {
	out := new(SignBlobResponse)
	err := c.cc.Invoke(ctx, CloudKeyManagementService_SignBlob_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudKeyManagementServiceClient) VerifyBlob(ctx context.Context, in *VerifyBlobRequest, opts ...grpc.CallOption) (*VerifyBlobResponse, error) {
	out := new(VerifyBlobResponse)
	err := c.cc.Invoke(ctx, CloudKeyManagementService_VerifyBlob_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudKeyManagementServiceClient) SignContent(ctx context.Context, in *SignContentRequest, opts ...grpc.CallOption) (*crypto.SignedContent, error) {
	out := new(crypto.SignedContent)
	err := c.cc.Invoke(ctx, CloudKeyManagementService_SignContent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudKeyManagementServiceClient) VerifySignedContent(ctx context.Context, in *VerifySignedContentRequest, opts ...grpc.CallOption) (*VerifySignedContentResponse, error) {
	out := new(VerifySignedContentResponse)
	err := c.cc.Invoke(ctx, CloudKeyManagementService_VerifySignedContent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudKeyManagementServiceClient) EncryptContent(ctx context.Context, in *EncryptContentRequest, opts ...grpc.CallOption) (*EncryptContentResponse, error) {
	out := new(EncryptContentResponse)
	err := c.cc.Invoke(ctx, CloudKeyManagementService_EncryptContent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudKeyManagementServiceClient) DecryptContent(ctx context.Context, in *DecryptContentRequest, opts ...grpc.CallOption) (*DecryptContentResponse, error) {
	out := new(DecryptContentResponse)
	err := c.cc.Invoke(ctx, CloudKeyManagementService_DecryptContent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudKeyManagementServiceClient) EncryptBlob(ctx context.Context, in *EncryptBlobRequest, opts ...grpc.CallOption) (*EncryptBlobResponse, error) {
	out := new(EncryptBlobResponse)
	err := c.cc.Invoke(ctx, CloudKeyManagementService_EncryptBlob_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudKeyManagementServiceClient) DecryptBlob(ctx context.Context, in *DecryptBlobRequest, opts ...grpc.CallOption) (*DecryptBlobResponse, error) {
	out := new(DecryptBlobResponse)
	err := c.cc.Invoke(ctx, CloudKeyManagementService_DecryptBlob_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CloudKeyManagementServiceServer is the server API for CloudKeyManagementService service.
// All implementations must embed UnimplementedCloudKeyManagementServiceServer
// for forward compatibility
type CloudKeyManagementServiceServer interface {
	// CreateKey creates a new cryptographic key.
	// New key is neither active nor used in a set.
	CreateKey(context.Context, *CreateKeyRequest) (*Key, error)
	// Lists the keys for a given project.
	ListKeys(context.Context, *ListKeysRequest) (*ListKeysResponse, error)
	// Get a key by its resource name.
	GetKey(context.Context, *GetKeyRequest) (*Key, error)
	// UpdateKey updates the specified cryptographic key.
	UpdateKey(context.Context, *UpdateKeyRequest) (*Key, error)
	// DeleteKey deletes the specified cryptographic key.
	// If the key is protected it will result in an error of type PERMISSION_DENIED.
	DeleteKey(context.Context, *DeleteKeyRequest) (*Key, error)
	// Creates a new key material and rotates the key.
	RotateKey(context.Context, *RotateKeyRequest) (*Key, error)
	// GetKeyMaterial returns the specified key material.
	GetKeyMaterial(context.Context, *GetKeyMaterialRequest) (*KeyMaterial, error)
	// ListKeyMaterials lists cryptographic keys that matches given request.
	ListKeyMaterials(context.Context, *ListKeyMaterialsRequest) (*ListKeyMaterialsResponse, error)
	// GetKeyMaterialCryptoKey returns the specified key material.
	GetKeyMaterialCryptoKey(context.Context, *GetKeyMaterialRequest) (*KeyMaterialContent, error)
	// Create a new key ring.
	CreateKeyRing(context.Context, *CreateKeyRingRequest) (*KeyRing, error)
	// List key rings.
	ListKeyRings(context.Context, *ListKeyRingsRequest) (*ListKeyRingsResponse, error)
	// Get key ring.
	GetKeyRing(context.Context, *GetKeyRingRequest) (*KeyRing, error)
	// ListKeyRingPublicKeys lists the asymmetric public keys for a given key rings key materials.
	ListKeyRingPublicKeys(context.Context, *ListKeyRingPublicKeysRequest) (*ListKeyRingPublicKeysResponse, error)
	// Update key ring.
	UpdateKeyRing(context.Context, *UpdateKeyRingRequest) (*KeyRing, error)
	// Delete key ring.
	DeleteKeyRing(context.Context, *DeleteKeyRingRequest) (*KeyRing, error)
	// SignBlob signs the given data with the given key.
	SignBlob(context.Context, *SignBlobRequest) (*SignBlobResponse, error)
	// VerifyBlob verifies the given signature with the given key.
	VerifyBlob(context.Context, *VerifyBlobRequest) (*VerifyBlobResponse, error)
	// SignContent signs the given data with the given key.
	SignContent(context.Context, *SignContentRequest) (*crypto.SignedContent, error)
	// Verify signed content verifies the given signature with the given key.
	VerifySignedContent(context.Context, *VerifySignedContentRequest) (*VerifySignedContentResponse, error)
	// Encrypts the input content with the given key.
	EncryptContent(context.Context, *EncryptContentRequest) (*EncryptContentResponse, error)
	// Decrypts the input content with the given key.
	DecryptContent(context.Context, *DecryptContentRequest) (*DecryptContentResponse, error)
	// EncryptBlob encrypts the input blob with the given key.
	EncryptBlob(context.Context, *EncryptBlobRequest) (*EncryptBlobResponse, error)
	// DecryptBlob decrypts the input blob with the given key.
	DecryptBlob(context.Context, *DecryptBlobRequest) (*DecryptBlobResponse, error)
	mustEmbedUnimplementedCloudKeyManagementServiceServer()
}

// UnimplementedCloudKeyManagementServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCloudKeyManagementServiceServer struct {
}

func (UnimplementedCloudKeyManagementServiceServer) CreateKey(context.Context, *CreateKeyRequest) (*Key, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateKey not implemented")
}
func (UnimplementedCloudKeyManagementServiceServer) ListKeys(context.Context, *ListKeysRequest) (*ListKeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListKeys not implemented")
}
func (UnimplementedCloudKeyManagementServiceServer) GetKey(context.Context, *GetKeyRequest) (*Key, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKey not implemented")
}
func (UnimplementedCloudKeyManagementServiceServer) UpdateKey(context.Context, *UpdateKeyRequest) (*Key, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateKey not implemented")
}
func (UnimplementedCloudKeyManagementServiceServer) DeleteKey(context.Context, *DeleteKeyRequest) (*Key, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteKey not implemented")
}
func (UnimplementedCloudKeyManagementServiceServer) RotateKey(context.Context, *RotateKeyRequest) (*Key, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RotateKey not implemented")
}
func (UnimplementedCloudKeyManagementServiceServer) GetKeyMaterial(context.Context, *GetKeyMaterialRequest) (*KeyMaterial, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKeyMaterial not implemented")
}
func (UnimplementedCloudKeyManagementServiceServer) ListKeyMaterials(context.Context, *ListKeyMaterialsRequest) (*ListKeyMaterialsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListKeyMaterials not implemented")
}
func (UnimplementedCloudKeyManagementServiceServer) GetKeyMaterialCryptoKey(context.Context, *GetKeyMaterialRequest) (*KeyMaterialContent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKeyMaterialCryptoKey not implemented")
}
func (UnimplementedCloudKeyManagementServiceServer) CreateKeyRing(context.Context, *CreateKeyRingRequest) (*KeyRing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateKeyRing not implemented")
}
func (UnimplementedCloudKeyManagementServiceServer) ListKeyRings(context.Context, *ListKeyRingsRequest) (*ListKeyRingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListKeyRings not implemented")
}
func (UnimplementedCloudKeyManagementServiceServer) GetKeyRing(context.Context, *GetKeyRingRequest) (*KeyRing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKeyRing not implemented")
}
func (UnimplementedCloudKeyManagementServiceServer) ListKeyRingPublicKeys(context.Context, *ListKeyRingPublicKeysRequest) (*ListKeyRingPublicKeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListKeyRingPublicKeys not implemented")
}
func (UnimplementedCloudKeyManagementServiceServer) UpdateKeyRing(context.Context, *UpdateKeyRingRequest) (*KeyRing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateKeyRing not implemented")
}
func (UnimplementedCloudKeyManagementServiceServer) DeleteKeyRing(context.Context, *DeleteKeyRingRequest) (*KeyRing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteKeyRing not implemented")
}
func (UnimplementedCloudKeyManagementServiceServer) SignBlob(context.Context, *SignBlobRequest) (*SignBlobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignBlob not implemented")
}
func (UnimplementedCloudKeyManagementServiceServer) VerifyBlob(context.Context, *VerifyBlobRequest) (*VerifyBlobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyBlob not implemented")
}
func (UnimplementedCloudKeyManagementServiceServer) SignContent(context.Context, *SignContentRequest) (*crypto.SignedContent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignContent not implemented")
}
func (UnimplementedCloudKeyManagementServiceServer) VerifySignedContent(context.Context, *VerifySignedContentRequest) (*VerifySignedContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifySignedContent not implemented")
}
func (UnimplementedCloudKeyManagementServiceServer) EncryptContent(context.Context, *EncryptContentRequest) (*EncryptContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EncryptContent not implemented")
}
func (UnimplementedCloudKeyManagementServiceServer) DecryptContent(context.Context, *DecryptContentRequest) (*DecryptContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecryptContent not implemented")
}
func (UnimplementedCloudKeyManagementServiceServer) EncryptBlob(context.Context, *EncryptBlobRequest) (*EncryptBlobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EncryptBlob not implemented")
}
func (UnimplementedCloudKeyManagementServiceServer) DecryptBlob(context.Context, *DecryptBlobRequest) (*DecryptBlobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecryptBlob not implemented")
}
func (UnimplementedCloudKeyManagementServiceServer) mustEmbedUnimplementedCloudKeyManagementServiceServer() {
}

// UnsafeCloudKeyManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CloudKeyManagementServiceServer will
// result in compilation errors.
type UnsafeCloudKeyManagementServiceServer interface {
	mustEmbedUnimplementedCloudKeyManagementServiceServer()
}

func RegisterCloudKeyManagementServiceServer(s grpc.ServiceRegistrar, srv CloudKeyManagementServiceServer) {
	s.RegisterService(&CloudKeyManagementService_ServiceDesc, srv)
}

func _CloudKeyManagementService_CreateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudKeyManagementServiceServer).CreateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudKeyManagementService_CreateKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudKeyManagementServiceServer).CreateKey(ctx, req.(*CreateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudKeyManagementService_ListKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudKeyManagementServiceServer).ListKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudKeyManagementService_ListKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudKeyManagementServiceServer).ListKeys(ctx, req.(*ListKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudKeyManagementService_GetKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudKeyManagementServiceServer).GetKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudKeyManagementService_GetKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudKeyManagementServiceServer).GetKey(ctx, req.(*GetKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudKeyManagementService_UpdateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudKeyManagementServiceServer).UpdateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudKeyManagementService_UpdateKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudKeyManagementServiceServer).UpdateKey(ctx, req.(*UpdateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudKeyManagementService_DeleteKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudKeyManagementServiceServer).DeleteKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudKeyManagementService_DeleteKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudKeyManagementServiceServer).DeleteKey(ctx, req.(*DeleteKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudKeyManagementService_RotateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudKeyManagementServiceServer).RotateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudKeyManagementService_RotateKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudKeyManagementServiceServer).RotateKey(ctx, req.(*RotateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudKeyManagementService_GetKeyMaterial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyMaterialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudKeyManagementServiceServer).GetKeyMaterial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudKeyManagementService_GetKeyMaterial_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudKeyManagementServiceServer).GetKeyMaterial(ctx, req.(*GetKeyMaterialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudKeyManagementService_ListKeyMaterials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKeyMaterialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudKeyManagementServiceServer).ListKeyMaterials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudKeyManagementService_ListKeyMaterials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudKeyManagementServiceServer).ListKeyMaterials(ctx, req.(*ListKeyMaterialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudKeyManagementService_GetKeyMaterialCryptoKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyMaterialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudKeyManagementServiceServer).GetKeyMaterialCryptoKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudKeyManagementService_GetKeyMaterialCryptoKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudKeyManagementServiceServer).GetKeyMaterialCryptoKey(ctx, req.(*GetKeyMaterialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudKeyManagementService_CreateKeyRing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKeyRingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudKeyManagementServiceServer).CreateKeyRing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudKeyManagementService_CreateKeyRing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudKeyManagementServiceServer).CreateKeyRing(ctx, req.(*CreateKeyRingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudKeyManagementService_ListKeyRings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKeyRingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudKeyManagementServiceServer).ListKeyRings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudKeyManagementService_ListKeyRings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudKeyManagementServiceServer).ListKeyRings(ctx, req.(*ListKeyRingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudKeyManagementService_GetKeyRing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyRingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudKeyManagementServiceServer).GetKeyRing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudKeyManagementService_GetKeyRing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudKeyManagementServiceServer).GetKeyRing(ctx, req.(*GetKeyRingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudKeyManagementService_ListKeyRingPublicKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKeyRingPublicKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudKeyManagementServiceServer).ListKeyRingPublicKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudKeyManagementService_ListKeyRingPublicKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudKeyManagementServiceServer).ListKeyRingPublicKeys(ctx, req.(*ListKeyRingPublicKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudKeyManagementService_UpdateKeyRing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateKeyRingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudKeyManagementServiceServer).UpdateKeyRing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudKeyManagementService_UpdateKeyRing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudKeyManagementServiceServer).UpdateKeyRing(ctx, req.(*UpdateKeyRingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudKeyManagementService_DeleteKeyRing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKeyRingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudKeyManagementServiceServer).DeleteKeyRing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudKeyManagementService_DeleteKeyRing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudKeyManagementServiceServer).DeleteKeyRing(ctx, req.(*DeleteKeyRingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudKeyManagementService_SignBlob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignBlobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudKeyManagementServiceServer).SignBlob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudKeyManagementService_SignBlob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudKeyManagementServiceServer).SignBlob(ctx, req.(*SignBlobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudKeyManagementService_VerifyBlob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyBlobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudKeyManagementServiceServer).VerifyBlob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudKeyManagementService_VerifyBlob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudKeyManagementServiceServer).VerifyBlob(ctx, req.(*VerifyBlobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudKeyManagementService_SignContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudKeyManagementServiceServer).SignContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudKeyManagementService_SignContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudKeyManagementServiceServer).SignContent(ctx, req.(*SignContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudKeyManagementService_VerifySignedContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifySignedContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudKeyManagementServiceServer).VerifySignedContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudKeyManagementService_VerifySignedContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudKeyManagementServiceServer).VerifySignedContent(ctx, req.(*VerifySignedContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudKeyManagementService_EncryptContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudKeyManagementServiceServer).EncryptContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudKeyManagementService_EncryptContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudKeyManagementServiceServer).EncryptContent(ctx, req.(*EncryptContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudKeyManagementService_DecryptContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudKeyManagementServiceServer).DecryptContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudKeyManagementService_DecryptContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudKeyManagementServiceServer).DecryptContent(ctx, req.(*DecryptContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudKeyManagementService_EncryptBlob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptBlobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudKeyManagementServiceServer).EncryptBlob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudKeyManagementService_EncryptBlob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudKeyManagementServiceServer).EncryptBlob(ctx, req.(*EncryptBlobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudKeyManagementService_DecryptBlob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptBlobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudKeyManagementServiceServer).DecryptBlob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudKeyManagementService_DecryptBlob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudKeyManagementServiceServer).DecryptBlob(ctx, req.(*DecryptBlobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CloudKeyManagementService_ServiceDesc is the grpc.ServiceDesc for CloudKeyManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CloudKeyManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blocky.kms.cloud.v1alpha.CloudKeyManagementService",
	HandlerType: (*CloudKeyManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateKey",
			Handler:    _CloudKeyManagementService_CreateKey_Handler,
		},
		{
			MethodName: "ListKeys",
			Handler:    _CloudKeyManagementService_ListKeys_Handler,
		},
		{
			MethodName: "GetKey",
			Handler:    _CloudKeyManagementService_GetKey_Handler,
		},
		{
			MethodName: "UpdateKey",
			Handler:    _CloudKeyManagementService_UpdateKey_Handler,
		},
		{
			MethodName: "DeleteKey",
			Handler:    _CloudKeyManagementService_DeleteKey_Handler,
		},
		{
			MethodName: "RotateKey",
			Handler:    _CloudKeyManagementService_RotateKey_Handler,
		},
		{
			MethodName: "GetKeyMaterial",
			Handler:    _CloudKeyManagementService_GetKeyMaterial_Handler,
		},
		{
			MethodName: "ListKeyMaterials",
			Handler:    _CloudKeyManagementService_ListKeyMaterials_Handler,
		},
		{
			MethodName: "GetKeyMaterialCryptoKey",
			Handler:    _CloudKeyManagementService_GetKeyMaterialCryptoKey_Handler,
		},
		{
			MethodName: "CreateKeyRing",
			Handler:    _CloudKeyManagementService_CreateKeyRing_Handler,
		},
		{
			MethodName: "ListKeyRings",
			Handler:    _CloudKeyManagementService_ListKeyRings_Handler,
		},
		{
			MethodName: "GetKeyRing",
			Handler:    _CloudKeyManagementService_GetKeyRing_Handler,
		},
		{
			MethodName: "ListKeyRingPublicKeys",
			Handler:    _CloudKeyManagementService_ListKeyRingPublicKeys_Handler,
		},
		{
			MethodName: "UpdateKeyRing",
			Handler:    _CloudKeyManagementService_UpdateKeyRing_Handler,
		},
		{
			MethodName: "DeleteKeyRing",
			Handler:    _CloudKeyManagementService_DeleteKeyRing_Handler,
		},
		{
			MethodName: "SignBlob",
			Handler:    _CloudKeyManagementService_SignBlob_Handler,
		},
		{
			MethodName: "VerifyBlob",
			Handler:    _CloudKeyManagementService_VerifyBlob_Handler,
		},
		{
			MethodName: "SignContent",
			Handler:    _CloudKeyManagementService_SignContent_Handler,
		},
		{
			MethodName: "VerifySignedContent",
			Handler:    _CloudKeyManagementService_VerifySignedContent_Handler,
		},
		{
			MethodName: "EncryptContent",
			Handler:    _CloudKeyManagementService_EncryptContent_Handler,
		},
		{
			MethodName: "DecryptContent",
			Handler:    _CloudKeyManagementService_DecryptContent_Handler,
		},
		{
			MethodName: "EncryptBlob",
			Handler:    _CloudKeyManagementService_EncryptBlob_Handler,
		},
		{
			MethodName: "DecryptBlob",
			Handler:    _CloudKeyManagementService_DecryptBlob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blocky/kms/cloud/v1alpha/cloud_kms_service.proto",
}
